import { internalMutation } from "./_generated/server";
import { internal } from "./_generated/api";

// ---------------------------------------------------------------------------
// Exercise seed data — split into categories for readability
// ---------------------------------------------------------------------------

const COMPOUNDS = [
  {
    name: "Barbell Back Squat",
    nameAr: "سكوات بالبار",
    category: "compound" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "squat rack"],
    difficulty: "intermediate" as const,
    instructions:
      "Stand with feet shoulder-width apart. Bar rests on upper traps. Squat until thighs are parallel to floor. Drive through heels to stand.",
    instructionsAr:
      "قف بعرض الكتفين. ضع البار على أعلى الظهر. انزل حتى يصبح الفخذ موازياً للأرض. ادفع بالكعبين للوقوف.",
    contraindications: ["knee", "lower back"],
    defaultSets: 4,
    defaultRepsMin: 6,
    defaultRepsMax: 10,
    defaultRestSeconds: 120,
    sortOrder: 1,
  },
  {
    name: "Barbell Bench Press",
    nameAr: "بنش برس بالبار",
    category: "compound" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate" as const,
    instructions:
      "Lie on bench, grip bar slightly wider than shoulders. Lower to chest, press back up. Keep feet flat on floor.",
    instructionsAr:
      "استلقِ على البنش وامسك البار بعرض أوسع من الكتفين. أنزل البار للصدر ثم ادفعه للأعلى.",
    contraindications: ["shoulder"],
    defaultSets: 4,
    defaultRepsMin: 6,
    defaultRepsMax: 10,
    defaultRestSeconds: 120,
    sortOrder: 2,
  },
  {
    name: "Conventional Deadlift",
    nameAr: "ديدلفت تقليدي",
    category: "compound" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["hamstrings", "glutes", "back"],
    secondaryMuscles: ["core", "quads"],
    equipment: ["barbell"],
    difficulty: "intermediate" as const,
    instructions:
      "Stand with feet hip-width, bar over mid-foot. Hinge at hips, grip bar. Drive through floor keeping back flat.",
    instructionsAr:
      "قف بعرض الوركين والبار فوق منتصف القدم. انحنِ من الورك وامسك البار. ادفع بالأرض مع إبقاء الظهر مستقيماً.",
    contraindications: ["lower back", "herniated disc"],
    defaultSets: 4,
    defaultRepsMin: 5,
    defaultRepsMax: 8,
    defaultRestSeconds: 150,
    sortOrder: 3,
  },
  {
    name: "Overhead Press",
    nameAr: "ضغط علوي بالبار",
    category: "compound" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate" as const,
    instructions:
      "Hold bar at shoulder height, press overhead until arms lock out. Keep core tight.",
    instructionsAr: "امسك البار عند مستوى الكتف واضغط للأعلى حتى تستقيم الذراعين. شد عضلات البطن.",
    contraindications: ["shoulder", "neck"],
    defaultSets: 3,
    defaultRepsMin: 6,
    defaultRepsMax: 10,
    defaultRestSeconds: 90,
    sortOrder: 4,
  },
  {
    name: "Barbell Row",
    nameAr: "تجديف بالبار",
    category: "compound" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["barbell"],
    difficulty: "intermediate" as const,
    instructions:
      "Hinge forward at hips, grip bar shoulder-width. Pull bar to lower chest, squeeze shoulder blades.",
    instructionsAr: "انحنِ للأمام من الورك وامسك البار بعرض الكتفين. اسحب البار نحو أسفل الصدر.",
    contraindications: ["lower back"],
    defaultSets: 4,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 5,
  },
  {
    name: "Pull-Up",
    nameAr: "سحب على البار",
    category: "compound" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back", "biceps"],
    secondaryMuscles: ["core", "rear_delts"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate" as const,
    instructions:
      "Hang with overhand grip. Pull body up until chin clears bar. Lower with control.",
    instructionsAr: "تعلق بقبضة علوية. اسحب جسمك حتى يتجاوز الذقن البار. انزل ببطء.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 5,
    defaultRepsMax: 10,
    defaultRestSeconds: 90,
    sortOrder: 6,
  },
  {
    name: "Dip",
    nameAr: "تمرين الغطس",
    category: "compound" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["shoulders"],
    equipment: ["dip bars"],
    difficulty: "intermediate" as const,
    instructions:
      "Support yourself on parallel bars. Lower body by bending elbows. Push back up to starting position.",
    instructionsAr: "ادعم جسمك على القضبان المتوازية. انزل بثني المرفقين. ادفع للأعلى.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 6,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 7,
  },
  {
    name: "Front Squat",
    nameAr: "سكوات أمامي",
    category: "compound" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "core"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell", "squat rack"],
    difficulty: "advanced" as const,
    instructions: "Bar rests on front delts. Elbows high. Squat deep with upright torso.",
    instructionsAr:
      "ضع البار على الدلتويد الأمامي. ارفع المرفقين. انزل عميقاً مع إبقاء الجذع مستقيماً.",
    contraindications: ["knee", "wrist"],
    defaultSets: 4,
    defaultRepsMin: 6,
    defaultRepsMax: 8,
    defaultRestSeconds: 120,
    sortOrder: 8,
  },
  {
    name: "Romanian Deadlift",
    nameAr: "ديدلفت روماني",
    category: "compound" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate" as const,
    instructions:
      "Hold bar at hip level. Push hips back, lower bar along shins. Feel stretch in hamstrings, return to start.",
    instructionsAr: "امسك البار عند مستوى الورك. ادفع الوركين للخلف وأنزل البار على الساقين.",
    contraindications: ["lower back"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 9,
  },
  {
    name: "Incline Bench Press",
    nameAr: "بنش مائل علوي",
    category: "compound" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest", "shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["barbell", "incline bench"],
    difficulty: "intermediate" as const,
    instructions: "Set bench to 30-45 degrees. Press bar from upper chest to lockout.",
    instructionsAr: "اضبط البنش على زاوية 30-45 درجة. اضغط البار من أعلى الصدر.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 10,
  },
  {
    name: "Leg Press",
    nameAr: "ضغط الأرجل",
    category: "compound" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["leg press machine"],
    difficulty: "beginner" as const,
    instructions:
      "Sit in machine with feet shoulder-width on platform. Lower until knees at 90 degrees, press back up.",
    instructionsAr: "اجلس في الجهاز وضع القدمين بعرض الكتفين. أنزل حتى الركبتين 90 درجة ثم ادفع.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 90,
    sortOrder: 11,
  },
  {
    name: "Lat Pulldown",
    nameAr: "سحب علوي",
    category: "compound" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions:
      "Sit at lat pulldown machine. Pull bar to upper chest, squeeze shoulder blades together.",
    instructionsAr: "اجلس على جهاز السحب العلوي. اسحب البار نحو أعلى الصدر.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 12,
  },
  {
    name: "Dumbbell Bench Press",
    nameAr: "بنش برس بالدمبل",
    category: "compound" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["dumbbells", "bench"],
    difficulty: "beginner" as const,
    instructions:
      "Lie on bench with dumbbells at chest level. Press up until arms extended. Lower with control.",
    instructionsAr: "استلقِ على البنش والدمبل عند مستوى الصدر. اضغط للأعلى حتى تمتد الذراعين.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 13,
  },
  {
    name: "Bulgarian Split Squat",
    nameAr: "سكوات بلغاري",
    category: "compound" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["dumbbells", "bench"],
    difficulty: "intermediate" as const,
    instructions:
      "Rear foot on bench, front foot forward. Lower until front thigh is parallel. Drive up through front heel.",
    instructionsAr:
      "ضع القدم الخلفية على البنش والأمامية للأمام. انزل حتى يصبح الفخذ الأمامي موازياً.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 14,
  },
  {
    name: "Goblet Squat",
    nameAr: "سكوات الكأس",
    category: "compound" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    equipment: ["dumbbell"],
    difficulty: "beginner" as const,
    instructions: "Hold dumbbell at chest. Squat down keeping chest up and elbows inside knees.",
    instructionsAr: "امسك الدمبل عند الصدر. انزل مع إبقاء الصدر مرفوعاً والمرفقين داخل الركبتين.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 60,
    sortOrder: 15,
  },
  {
    name: "T-Bar Row",
    nameAr: "تجديف تي بار",
    category: "compound" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["t-bar row", "barbell"],
    difficulty: "intermediate" as const,
    instructions: "Straddle bar, grip handle. Pull to chest keeping back flat. Squeeze at top.",
    instructionsAr: "قف فوق البار وامسك المقبض. اسحب نحو الصدر مع إبقاء الظهر مستقيماً.",
    contraindications: ["lower back"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 16,
  },
  {
    name: "Sumo Deadlift",
    nameAr: "ديدلفت سومو",
    category: "compound" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["glutes", "quads"],
    secondaryMuscles: ["hamstrings", "back"],
    equipment: ["barbell"],
    difficulty: "advanced" as const,
    instructions:
      "Wide stance, grip inside knees. Push floor away, keep chest up throughout the lift.",
    instructionsAr:
      "وقفة واسعة، امسك البار داخل الركبتين. ادفع الأرض بعيداً مع إبقاء الصدر مرفوعاً.",
    contraindications: ["hip", "lower back"],
    defaultSets: 4,
    defaultRepsMin: 5,
    defaultRepsMax: 8,
    defaultRestSeconds: 150,
    sortOrder: 17,
  },
  {
    name: "Chin-Up",
    nameAr: "سحب بقبضة سفلية",
    category: "compound" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back", "biceps"],
    secondaryMuscles: ["core"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate" as const,
    instructions: "Hang with underhand (supinated) grip. Pull up until chin clears bar.",
    instructionsAr: "تعلق بقبضة سفلية. اسحب جسمك حتى يتجاوز الذقن البار.",
    contraindications: ["shoulder", "elbow"],
    defaultSets: 3,
    defaultRepsMin: 5,
    defaultRepsMax: 10,
    defaultRestSeconds: 90,
    sortOrder: 18,
  },
  {
    name: "Hack Squat",
    nameAr: "هاك سكوات",
    category: "compound" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: ["hack squat machine"],
    difficulty: "beginner" as const,
    instructions:
      "Position shoulders under pads, feet shoulder-width. Lower until 90 degrees, press up.",
    instructionsAr: "ضع الكتفين تحت الوسائد. انزل حتى 90 درجة ثم ادفع للأعلى.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 90,
    sortOrder: 19,
  },
  {
    name: "Seated Cable Row",
    nameAr: "تجديف بالكيبل جالس",
    category: "compound" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions:
      "Sit at cable row. Pull handle to lower chest, squeeze shoulder blades. Return slowly.",
    instructionsAr: "اجلس على جهاز التجديف. اسحب المقبض نحو أسفل الصدر.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 20,
  },
  {
    name: "Trap Bar Deadlift",
    nameAr: "ديدلفت بالبار السداسي",
    category: "compound" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["hamstrings", "glutes", "quads"],
    secondaryMuscles: ["back", "core"],
    equipment: ["trap bar"],
    difficulty: "intermediate" as const,
    instructions: "Stand inside trap bar. Grip handles, push through floor keeping chest up.",
    instructionsAr: "قف داخل البار السداسي. امسك المقابض وادفع بالأرض مع إبقاء الصدر مرفوعاً.",
    contraindications: ["lower back"],
    defaultSets: 4,
    defaultRepsMin: 5,
    defaultRepsMax: 8,
    defaultRestSeconds: 150,
    sortOrder: 101,
  },
  {
    name: "Pendlay Row",
    nameAr: "تجديف بندلاي",
    category: "compound" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts", "core"],
    equipment: ["barbell"],
    difficulty: "advanced" as const,
    instructions:
      "Bar on floor each rep. Hinge forward, explosively row to lower chest. Lower to floor.",
    instructionsAr: "البار على الأرض كل تكرار. انحنِ للأمام واسحب بقوة نحو أسفل الصدر.",
    contraindications: ["lower back"],
    defaultSets: 4,
    defaultRepsMin: 5,
    defaultRepsMax: 8,
    defaultRestSeconds: 120,
    sortOrder: 102,
  },
  {
    name: "Landmine Press",
    nameAr: "ضغط لاندماين",
    category: "compound" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["shoulders", "chest"],
    secondaryMuscles: ["triceps", "core"],
    equipment: ["barbell", "landmine"],
    difficulty: "intermediate" as const,
    instructions: "Hold end of barbell at shoulder. Press up and forward. Control the descent.",
    instructionsAr: "امسك طرف البار عند الكتف. اضغط للأعلى وللأمام. تحكم بالنزول.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 103,
  },
  {
    name: "Push Press",
    nameAr: "ضغط دفعي",
    category: "compound" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core", "quads"],
    equipment: ["barbell"],
    difficulty: "advanced" as const,
    instructions:
      "Bar at shoulders. Slight knee dip then explosively press overhead using leg drive.",
    instructionsAr:
      "البار عند الكتفين. ثني خفيف بالركبتين ثم اضغط بقوة للأعلى باستخدام دفع الأرجل.",
    contraindications: ["shoulder", "knee"],
    defaultSets: 4,
    defaultRepsMin: 5,
    defaultRepsMax: 8,
    defaultRestSeconds: 120,
    sortOrder: 104,
  },
  {
    name: "Single-Leg Romanian Deadlift",
    nameAr: "ديدلفت روماني بساق واحدة",
    category: "compound" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["core", "back"],
    equipment: ["dumbbell"],
    difficulty: "intermediate" as const,
    instructions: "Stand on one leg. Hinge forward extending rear leg back. Return to standing.",
    instructionsAr: "قف على ساق واحدة. انحنِ للأمام مع مد الساق الخلفية. عُد للوقوف.",
    contraindications: ["lower back", "knee"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 105,
  },
  {
    name: "Smith Machine Squat",
    nameAr: "سكوات سميث",
    category: "compound" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["smith machine"],
    difficulty: "beginner" as const,
    instructions: "Bar on upper back in Smith machine. Feet slightly forward. Squat to parallel.",
    instructionsAr: "البار على أعلى الظهر في جهاز سميث. القدمين للأمام قليلاً. انزل حتى التوازي.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 106,
  },
  {
    name: "Cable Pullthrough",
    nameAr: "سحب كيبل بين الأرجل",
    category: "compound" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions: "Face away from low cable. Pull rope through legs by driving hips forward.",
    instructionsAr: "واجه بعيداً عن الكيبل السفلي. اسحب الحبل بين الأرجل بدفع الوركين للأمام.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 60,
    sortOrder: 107,
  },
  {
    name: "Floor Press",
    nameAr: "ضغط أرضي",
    category: "compound" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate" as const,
    instructions: "Lie on floor. Press bar from chest to lockout. Elbows touch floor between reps.",
    instructionsAr:
      "استلقِ على الأرض. اضغط البار من الصدر حتى القفل. المرفقان يلمسان الأرض بين التكرارات.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 6,
    defaultRepsMax: 10,
    defaultRestSeconds: 90,
    sortOrder: 108,
  },
];

const ACCESSORY = [
  {
    name: "Dumbbell Shoulder Press",
    nameAr: "ضغط كتف بالدمبل",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions: "Sit on bench, press dumbbells overhead. Lower to ear level and press back up.",
    instructionsAr: "اجلس على البنش واضغط الدمبل للأعلى. أنزل لمستوى الأذن ثم اضغط.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 21,
  },
  {
    name: "Dumbbell Lunges",
    nameAr: "طعنات بالدمبل",
    category: "accessory" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions:
      "Step forward, lower until both knees at 90 degrees. Push back to starting position.",
    instructionsAr: "اخطو للأمام وانزل حتى تصبح الركبتان 90 درجة. ارجع للوضع الأول.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 22,
  },
  {
    name: "Face Pull",
    nameAr: "سحب للوجه",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["rear_delts", "shoulders"],
    secondaryMuscles: ["back"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions:
      "Set cable at face height with rope. Pull toward face, externally rotating at end.",
    instructionsAr: "اضبط الكيبل عند مستوى الوجه بالحبل. اسحب نحو الوجه مع دوران خارجي.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 60,
    sortOrder: 23,
  },
  {
    name: "Cable Lateral Raise",
    nameAr: "رفع جانبي بالكيبل",
    category: "accessory" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions: "Stand sideways to cable. Raise arm to shoulder height. Lower with control.",
    instructionsAr: "قف جانبياً للكيبل. ارفع الذراع لمستوى الكتف. أنزل ببطء.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 24,
  },
  {
    name: "Incline Dumbbell Curl",
    nameAr: "كيرل مائل بالدمبل",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells", "incline bench"],
    difficulty: "beginner" as const,
    instructions: "Sit on incline bench. Curl dumbbells with arms fully extended at bottom.",
    instructionsAr: "اجلس على البنش المائل. ارفع الدمبل مع تمديد الذراعين بالكامل في الأسفل.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    sortOrder: 25,
  },
  {
    name: "Tricep Pushdown",
    nameAr: "تمديد ترايسبس بالكيبل",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions: "Stand at cable, push rope/bar down until arms fully extend. Keep elbows pinned.",
    instructionsAr: "قف عند الكيبل وادفع للأسفل حتى تمتد الذراعين. ثبّت المرفقين.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 26,
  },
  {
    name: "Hip Thrust",
    nameAr: "دفع الورك",
    category: "accessory" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "bench"],
    difficulty: "beginner" as const,
    instructions: "Back against bench, bar over hips. Drive hips up, squeeze glutes at top.",
    instructionsAr:
      "الظهر على البنش والبار فوق الوركين. ادفع الوركين للأعلى واضغط على عضلات المؤخرة.",
    contraindications: ["hip"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 60,
    sortOrder: 27,
  },
  {
    name: "Leg Curl",
    nameAr: "ثني الأرجل",
    category: "accessory" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["leg curl machine"],
    difficulty: "beginner" as const,
    instructions: "Lie face down on machine. Curl pad toward glutes. Lower with control.",
    instructionsAr: "استلقِ على الجهاز. ارفع الوسادة نحو المؤخرة. أنزل ببطء.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 60,
    sortOrder: 28,
  },
  {
    name: "Leg Extension",
    nameAr: "تمديد الأرجل",
    category: "accessory" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: ["leg extension machine"],
    difficulty: "beginner" as const,
    instructions: "Sit on machine. Extend legs until straight. Lower slowly.",
    instructionsAr: "اجلس على الجهاز. مدد الساقين حتى تستقيم. أنزل ببطء.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 29,
  },
  {
    name: "Dumbbell Row",
    nameAr: "تجديف بالدمبل",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbell", "bench"],
    difficulty: "beginner" as const,
    instructions: "One hand and knee on bench. Row dumbbell to hip, squeeze back muscles.",
    instructionsAr: "يد وركبة على البنش. اسحب الدمبل نحو الورك واضغط عضلات الظهر.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 30,
  },
  {
    name: "Close Grip Bench Press",
    nameAr: "بنش قبضة ضيقة",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate" as const,
    instructions:
      "Grip bar shoulder-width. Lower to lower chest, press up keeping elbows close to body.",
    instructionsAr: "امسك البار بعرض الكتفين. أنزل لأسفل الصدر واضغط مع إبقاء المرفقين قريبين.",
    contraindications: ["shoulder", "wrist"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 31,
  },
  {
    name: "Cable Fly",
    nameAr: "تفتيح بالكيبل",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions:
      "Stand between cables. Bring handles together in front of chest with slight elbow bend.",
    instructionsAr: "قف بين الكيبلات. اجمع المقابض أمام الصدر مع ثني خفيف في المرفق.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 32,
  },
  {
    name: "Reverse Fly",
    nameAr: "تفتيح خلفي",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["back"],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions: "Bend forward, raise dumbbells out to sides. Squeeze shoulder blades together.",
    instructionsAr: "انحنِ للأمام وارفع الدمبل للجانبين. اضغط لوحي الكتف معاً.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 33,
  },
  {
    name: "Farmer's Walk",
    nameAr: "مشي المزارع",
    category: "accessory" as const,
    movementPattern: "carry" as const,
    primaryMuscles: ["core", "shoulders"],
    secondaryMuscles: ["back", "quads"],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions: "Hold heavy dumbbells at sides. Walk with upright posture for distance or time.",
    instructionsAr: "امسك دمبل ثقيل في كل يد. امشِ بوضعية مستقيمة لمسافة أو وقت محدد.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 30,
    defaultRepsMax: 40,
    defaultRestSeconds: 60,
    sortOrder: 34,
  },
  {
    name: "Dumbbell Fly",
    nameAr: "تفتيح بالدمبل",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["dumbbells", "bench"],
    difficulty: "beginner" as const,
    instructions:
      "Lie on bench. Lower dumbbells out to sides with slight bend. Bring back to start.",
    instructionsAr: "استلقِ على البنش. أنزل الدمبل للجانبين بثني خفيف. ارجعهم للبداية.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 35,
  },
  {
    name: "Good Morning",
    nameAr: "صباح الخير",
    category: "accessory" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["hamstrings", "back"],
    secondaryMuscles: ["glutes", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate" as const,
    instructions:
      "Bar on upper back. Hinge at hips pushing them back. Return when you feel hamstring stretch.",
    instructionsAr:
      "ضع البار على أعلى الظهر. انحنِ من الورك. عُد عند الشعور بتمدد العضلات الخلفية.",
    contraindications: ["lower back"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 36,
  },
  {
    name: "Chest Supported Row",
    nameAr: "تجديف مدعوم بالصدر",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["dumbbells", "incline bench"],
    difficulty: "beginner" as const,
    instructions: "Lie face down on incline bench. Row dumbbells up squeezing shoulder blades.",
    instructionsAr: "استلقِ على البنش المائل. اسحب الدمبل للأعلى مع ضغط لوحي الكتف.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 37,
  },
  {
    name: "Step-Up",
    nameAr: "صعود الدرج بالدمبل",
    category: "accessory" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbells", "bench"],
    difficulty: "beginner" as const,
    instructions:
      "Hold dumbbells, step up onto bench. Drive through front leg. Step down with control.",
    instructionsAr: "امسك الدمبل واصعد على البنش. ادفع بالرجل الأمامية. انزل ببطء.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 38,
  },
  {
    name: "Arnold Press",
    nameAr: "أرنولد برس",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"],
    difficulty: "intermediate" as const,
    instructions: "Start with palms facing you. Rotate and press overhead simultaneously.",
    instructionsAr: "ابدأ بالكفين نحوك. قم بالدوران والضغط للأعلى في نفس الوقت.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 39,
  },
  {
    name: "Barbell Curl",
    nameAr: "كيرل بالبار",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["barbell"],
    difficulty: "beginner" as const,
    instructions: "Stand with barbell, underhand grip. Curl to shoulders keeping elbows at sides.",
    instructionsAr: "قف بالبار بقبضة سفلية. ارفع للكتفين مع تثبيت المرفقين.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 121,
  },
  {
    name: "EZ Bar Curl",
    nameAr: "كيرل بالبار المنحني",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["ez bar"],
    difficulty: "beginner" as const,
    instructions: "Grip EZ bar at angled handles. Curl up with reduced wrist strain.",
    instructionsAr: "امسك البار المنحني عند الزوايا. ارفع مع ضغط أقل على الرسغ.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    sortOrder: 122,
  },
  {
    name: "Spider Curl",
    nameAr: "كيرل العنكبوت",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells", "incline bench"],
    difficulty: "intermediate" as const,
    instructions: "Lie face down on incline bench. Arms hang straight. Curl dumbbells up.",
    instructionsAr: "استلقِ على البنش المائل والذراعين معلقتين. ارفع الدمبل للأعلى.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    sortOrder: 123,
  },
  {
    name: "Machine Chest Press",
    nameAr: "ضغط صدر بالجهاز",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["chest press machine"],
    difficulty: "beginner" as const,
    instructions: "Sit in machine. Push handles forward until arms extended. Return slowly.",
    instructionsAr: "اجلس في الجهاز. ادفع المقابض للأمام حتى تمتد الذراعين. ارجع ببطء.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 124,
  },
  {
    name: "Machine Shoulder Press",
    nameAr: "ضغط كتف بالجهاز",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["shoulder press machine"],
    difficulty: "beginner" as const,
    instructions: "Sit in machine. Press handles overhead. Lower with control.",
    instructionsAr: "اجلس في الجهاز. اضغط المقابض للأعلى. أنزل بتحكم.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 125,
  },
  {
    name: "Glute Bridge",
    nameAr: "جسر المؤخرة",
    category: "accessory" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Lie on back, feet flat. Drive hips up squeezing glutes. Lower slowly.",
    instructionsAr: "استلقِ على الظهر والقدمين مسطحتين. ادفع الوركين للأعلى واضغط المؤخرة.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 126,
  },
  {
    name: "Nordic Hamstring Curl",
    nameAr: "كيرل نوردي",
    category: "accessory" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes"],
    equipment: [],
    difficulty: "advanced" as const,
    instructions:
      "Kneel with ankles anchored. Slowly lower body forward controlling with hamstrings. Push back up.",
    instructionsAr: "اركع مع تثبيت الكاحلين. انزل ببطء للأمام بالتحكم بالعضلات الخلفية.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 4,
    defaultRepsMax: 8,
    defaultRestSeconds: 90,
    sortOrder: 127,
  },
  {
    name: "Rear Delt Machine",
    nameAr: "جهاز الدلتويد الخلفي",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["back"],
    equipment: ["rear delt machine"],
    difficulty: "beginner" as const,
    instructions: "Sit facing machine. Push handles back squeezing shoulder blades. Return slowly.",
    instructionsAr: "اجلس مواجهاً للجهاز. ادفع المقابض للخلف واضغط لوحي الكتف.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 128,
  },
  {
    name: "Cable Crossover",
    nameAr: "كروس أوفر بالكيبل",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "intermediate" as const,
    instructions: "Stand between high cables. Bring handles down and together in front of hips.",
    instructionsAr: "قف بين الكيبلات العلوية. اجمع المقابض للأسفل وللأمام أمام الوركين.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 129,
  },
  {
    name: "Incline Dumbbell Row",
    nameAr: "تجديف مائل بالدمبل",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["dumbbells", "incline bench"],
    difficulty: "beginner" as const,
    instructions: "Lie chest down on incline bench. Row dumbbells up squeezing back.",
    instructionsAr: "استلقِ على صدرك على البنش المائل. اسحب الدمبل للأعلى مع ضغط الظهر.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 130,
  },
  {
    name: "Decline Bench Press",
    nameAr: "بنش مائل سفلي",
    category: "accessory" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["barbell", "decline bench"],
    difficulty: "intermediate" as const,
    instructions: "Lie on decline bench. Lower bar to lower chest. Press back up.",
    instructionsAr: "استلقِ على البنش المائل السفلي. أنزل البار لأسفل الصدر. اضغط للأعلى.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 90,
    sortOrder: 131,
  },
  {
    name: "Dumbbell Pullover",
    nameAr: "بول أوفر بالدمبل",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["chest", "back"],
    secondaryMuscles: ["core"],
    equipment: ["dumbbell", "bench"],
    difficulty: "intermediate" as const,
    instructions:
      "Lie on bench, hold dumbbell over chest. Lower behind head with slight bend. Pull back over.",
    instructionsAr: "استلقِ على البنش وامسك الدمبل فوق الصدر. أنزل خلف الرأس. ارجع.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 132,
  },
  {
    name: "Upright Row",
    nameAr: "تجديف عمودي",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["biceps"],
    equipment: ["barbell"],
    difficulty: "intermediate" as const,
    instructions: "Hold bar with narrow grip. Pull up to chin level leading with elbows.",
    instructionsAr: "امسك البار بقبضة ضيقة. اسحب للأعلى لمستوى الذقن بقيادة المرفقين.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 133,
  },
  {
    name: "Cable Woodchop",
    nameAr: "قطع الخشب بالكيبل",
    category: "accessory" as const,
    movementPattern: "rotation" as const,
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions: "Stand sideways to cable. Pull from high to low with rotation. Control return.",
    instructionsAr: "قف جانبياً للكيبل. اسحب من الأعلى للأسفل مع دوران. تحكم بالرجوع.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 134,
  },
  {
    name: "Pallof Press",
    nameAr: "ضغط بالوف",
    category: "accessory" as const,
    movementPattern: "rotation" as const,
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions:
      "Stand sideways to cable at chest height. Press handle forward resisting rotation. Return.",
    instructionsAr: "قف جانبياً للكيبل عند مستوى الصدر. اضغط المقبض للأمام مع مقاومة الدوران.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    sortOrder: 135,
  },
  {
    name: "Dead Hang",
    nameAr: "التعلق الميت",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back", "shoulders"],
    secondaryMuscles: ["forearms", "core"],
    equipment: ["pull-up bar"],
    difficulty: "beginner" as const,
    instructions: "Hang from bar with straight arms. Engage shoulders slightly. Hold for time.",
    instructionsAr: "تعلق من البار بذراعين مستقيمتين. شد الكتفين قليلاً. ثبت لوقت.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 20,
    defaultRepsMax: 30,
    defaultRestSeconds: 60,
    sortOrder: 136,
  },
  {
    name: "Landmine Row",
    nameAr: "تجديف لاندماين",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "core"],
    equipment: ["barbell", "landmine"],
    difficulty: "intermediate" as const,
    instructions: "Straddle barbell end. Grip with one or both hands. Row to hip.",
    instructionsAr: "قف فوق طرف البار. امسك بيد أو يدين. اسحب نحو الورك.",
    contraindications: ["lower back"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 137,
  },
  {
    name: "Machine Row",
    nameAr: "تجديف بالجهاز",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["row machine"],
    difficulty: "beginner" as const,
    instructions:
      "Sit at row machine with chest against pad. Pull handles back squeezing shoulder blades.",
    instructionsAr: "اجلس على جهاز التجديف والصدر على الوسادة. اسحب المقابض للخلف.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 138,
  },
  {
    name: "Leg Press Narrow Stance",
    nameAr: "ضغط أرجل قبضة ضيقة",
    category: "accessory" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: ["leg press machine"],
    difficulty: "beginner" as const,
    instructions: "Sit in leg press with feet close together and low on platform. Press and lower.",
    instructionsAr: "اجلس في جهاز ضغط الأرجل والقدمين قريبتين وأسفل المنصة. اضغط وأنزل.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 90,
    sortOrder: 139,
  },
  {
    name: "Seated Row Wide Grip",
    nameAr: "تجديف جالس قبضة واسعة",
    category: "accessory" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["back", "rear_delts"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions: "Sit at cable row with wide bar attachment. Pull to upper abdomen.",
    instructionsAr: "اجلس على جهاز التجديف بمقبض واسع. اسحب نحو أعلى البطن.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 140,
  },
];

const ISOLATION = [
  {
    name: "Bicep Curl",
    nameAr: "كيرل بايسبس",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions: "Stand holding dumbbells. Curl up keeping elbows stationary. Lower slowly.",
    instructionsAr: "قف وامسك الدمبل. ارفع بالتناوب مع تثبيت المرفقين. أنزل ببطء.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 41,
  },
  {
    name: "Hammer Curl",
    nameAr: "كيرل مطرقة",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions: "Hold dumbbells with neutral grip (palms facing each other). Curl up.",
    instructionsAr: "امسك الدمبل بقبضة محايدة (الكفين نحو بعضهما). ارفع للأعلى.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    sortOrder: 42,
  },
  {
    name: "Overhead Tricep Extension",
    nameAr: "تمديد ترايسبس فوق الرأس",
    category: "isolation" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    difficulty: "beginner" as const,
    instructions: "Hold dumbbell overhead with both hands. Lower behind head. Extend back up.",
    instructionsAr: "امسك الدمبل فوق الرأس بكلتا اليدين. أنزل خلف الرأس. مدد للأعلى.",
    contraindications: ["elbow", "shoulder"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 43,
  },
  {
    name: "Lateral Raise",
    nameAr: "رفع جانبي",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions: "Stand with dumbbells at sides. Raise to shoulder height. Lower slowly.",
    instructionsAr: "قف والدمبل بجانبيك. ارفع لمستوى الكتف. أنزل ببطء.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 44,
  },
  {
    name: "Front Raise",
    nameAr: "رفع أمامي",
    category: "isolation" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions: "Hold dumbbells in front. Raise one or both arms to shoulder height in front.",
    instructionsAr: "امسك الدمبل أمامك. ارفع للأعلى حتى مستوى الكتف.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 45,
  },
  {
    name: "Calf Raise",
    nameAr: "رفع الساق",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["calf raise machine"],
    difficulty: "beginner" as const,
    instructions:
      "Stand on edge of platform. Rise up on toes. Lower below platform level for full stretch.",
    instructionsAr: "قف على حافة المنصة. ارتفع على أطراف أصابعك. انزل تحت مستوى المنصة.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 15,
    defaultRepsMax: 20,
    defaultRestSeconds: 45,
    sortOrder: 46,
  },
  {
    name: "Cable Curl",
    nameAr: "كيرل بالكيبل",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions: "Stand at cable machine with bar attachment. Curl up keeping elbows at sides.",
    instructionsAr: "قف عند جهاز الكيبل. ارفع البار مع تثبيت المرفقين بجانبيك.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 47,
  },
  {
    name: "Skull Crusher",
    nameAr: "سكل كراشر",
    category: "isolation" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["ez bar", "bench"],
    difficulty: "intermediate" as const,
    instructions:
      "Lie on bench with EZ bar. Lower to forehead by bending elbows only. Extend back up.",
    instructionsAr: "استلقِ على البنش بالبار المنحني. أنزل للجبهة بثني المرفقين فقط. مدد للأعلى.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 48,
  },
  {
    name: "Concentration Curl",
    nameAr: "كيرل مركز",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    difficulty: "beginner" as const,
    instructions: "Sit on bench, elbow against inner thigh. Curl dumbbell up. Lower slowly.",
    instructionsAr: "اجلس على البنش والمرفق على الفخذ الداخلي. ارفع الدمبل. أنزل ببطء.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    sortOrder: 49,
  },
  {
    name: "Preacher Curl",
    nameAr: "كيرل على المنصة",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["ez bar", "preacher bench"],
    difficulty: "beginner" as const,
    instructions: "Rest arms on preacher bench. Curl up slowly. Lower under control.",
    instructionsAr: "ضع الذراعين على منصة البريشر. ارفع ببطء. أنزل بتحكم.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    sortOrder: 50,
  },
  {
    name: "Kickback",
    nameAr: "كيكباك ترايسبس",
    category: "isolation" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    difficulty: "beginner" as const,
    instructions: "Bend forward, upper arm parallel to floor. Extend forearm back. Squeeze tricep.",
    instructionsAr: "انحنِ للأمام والذراع العلوي موازٍ للأرض. مدد الساعد للخلف.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 51,
  },
  {
    name: "Shrug",
    nameAr: "شرج",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions: "Hold heavy dumbbells. Shrug shoulders up toward ears. Hold briefly, lower.",
    instructionsAr: "امسك دمبل ثقيل. ارفع الكتفين نحو الأذنين. ثبت لحظة ثم أنزل.",
    contraindications: ["neck"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 52,
  },
  {
    name: "Wrist Curl",
    nameAr: "كيرل الرسغ",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "beginner" as const,
    instructions: "Sit with forearms on thighs, wrists over edge. Curl bar up using wrists only.",
    instructionsAr: "اجلس والساعدين على الفخذين والرسغين فوق الحافة. ارفع بالرسغين فقط.",
    contraindications: ["wrist"],
    defaultSets: 3,
    defaultRepsMin: 15,
    defaultRepsMax: 20,
    defaultRestSeconds: 30,
    sortOrder: 53,
  },
  {
    name: "Seated Calf Raise",
    nameAr: "رفع ساق جالس",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["seated calf machine"],
    difficulty: "beginner" as const,
    instructions: "Sit with knees under pad. Rise on toes, pause at top. Lower with control.",
    instructionsAr: "اجلس والركبتين تحت الوسادة. ارتفع على الأصابع. أنزل ببطء.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 15,
    defaultRepsMax: 20,
    defaultRestSeconds: 45,
    sortOrder: 54,
  },
  {
    name: "Cable Kickback",
    nameAr: "كيكباك بالكيبل",
    category: "isolation" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions: "Attach ankle strap, face machine. Kick leg back squeezing glute. Return slowly.",
    instructionsAr: "ربّط شريط الكاحل وواجه الجهاز. اركل للخلف واضغط المؤخرة.",
    contraindications: ["hip"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 55,
  },
  {
    name: "Adductor Machine",
    nameAr: "جهاز العضلة المقربة",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["adductors"],
    secondaryMuscles: [],
    equipment: ["adductor machine"],
    difficulty: "beginner" as const,
    instructions: "Sit with pads on inner thighs. Squeeze legs together. Return slowly.",
    instructionsAr: "اجلس والوسائد على الفخذين الداخليين. اضغط الساقين معاً. ارجع ببطء.",
    contraindications: ["hip"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 56,
  },
  {
    name: "Abductor Machine",
    nameAr: "جهاز العضلة المبعدة",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: ["abductor machine"],
    difficulty: "beginner" as const,
    instructions: "Sit with pads on outer thighs. Push legs apart. Return slowly.",
    instructionsAr: "اجلس والوسائد على الفخذين الخارجيين. ادفع الساقين بعيداً. ارجع ببطء.",
    contraindications: ["hip"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 57,
  },
  {
    name: "Pec Deck",
    nameAr: "بك دك",
    category: "isolation" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    equipment: ["pec deck machine"],
    difficulty: "beginner" as const,
    instructions: "Sit with arms on pads. Bring pads together in front. Return slowly.",
    instructionsAr: "اجلس والذراعين على الوسائد. اجمع الوسائد للأمام. ارجع ببطء.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 141,
  },
  {
    name: "Cable Tricep Overhead Extension",
    nameAr: "تمديد ترايسبس علوي بالكيبل",
    category: "isolation" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions: "Face away from cable with rope overhead. Extend arms forward and up.",
    instructionsAr: "واجه بعيداً عن الكيبل والحبل فوق الرأس. مدد الذراعين للأمام وللأعلى.",
    contraindications: ["elbow", "shoulder"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 142,
  },
  {
    name: "Cross-Body Hammer Curl",
    nameAr: "كيرل مطرقة متقاطع",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbell"],
    difficulty: "beginner" as const,
    instructions: "Curl dumbbell across body toward opposite shoulder with neutral grip.",
    instructionsAr: "ارفع الدمبل عبر الجسم نحو الكتف المقابل بقبضة محايدة.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    sortOrder: 143,
  },
  {
    name: "Reverse Curl",
    nameAr: "كيرل معكوس",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["forearms", "biceps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "beginner" as const,
    instructions: "Hold bar with overhand grip. Curl up keeping wrists straight.",
    instructionsAr: "امسك البار بقبضة علوية. ارفع مع إبقاء الرسغين مستقيمين.",
    contraindications: ["wrist"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 144,
  },
  {
    name: "Dumbbell Shrug",
    nameAr: "شرج بالدمبل",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner" as const,
    instructions: "Hold dumbbells at sides. Shrug shoulders up to ears. Hold briefly, lower.",
    instructionsAr: "امسك الدمبل بجانبيك. ارفع الكتفين نحو الأذنين. ثبت لحظة.",
    contraindications: ["neck"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 145,
  },
  {
    name: "Machine Calf Raise",
    nameAr: "رفع ساق بالجهاز",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["calf raise machine"],
    difficulty: "beginner" as const,
    instructions:
      "Stand in standing calf machine. Rise on toes, pause at top. Lower for full stretch.",
    instructionsAr: "قف في جهاز رفع الساق. ارتفع على الأصابع. أنزل لتمدد كامل.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 15,
    defaultRepsMax: 20,
    defaultRestSeconds: 45,
    sortOrder: 146,
  },
  {
    name: "Inner Thigh Machine",
    nameAr: "جهاز الفخذ الداخلي",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["adductors"],
    secondaryMuscles: [],
    equipment: ["adductor machine"],
    difficulty: "beginner" as const,
    instructions: "Sit with pads on inner thighs. Squeeze legs together. Return slowly.",
    instructionsAr: "اجلس والوسائد على الفخذين الداخليين. اضغط الساقين معاً.",
    contraindications: ["hip"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 147,
  },
  {
    name: "Single-Leg Calf Raise",
    nameAr: "رفع ساق بقدم واحدة",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Stand on one foot on a step edge. Rise on toes. Lower below step level.",
    instructionsAr: "قف على قدم واحدة على حافة درج. ارتفع على الأصابع. أنزل تحت المستوى.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 148,
  },
  {
    name: "Rope Face Pull",
    nameAr: "سحب حبل للوجه",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions:
      "Set cable high with rope. Pull toward face separating rope ends. External rotate.",
    instructionsAr: "اضبط الكيبل عالياً بالحبل. اسحب نحو الوجه مع فصل طرفي الحبل.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 149,
  },
  {
    name: "EZ Bar Skull Crusher",
    nameAr: "سكل كراشر بالبار المنحني",
    category: "isolation" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["ez bar", "bench"],
    difficulty: "intermediate" as const,
    instructions:
      "Lie on bench with EZ bar. Lower to forehead bending only at elbows. Extend back.",
    instructionsAr: "استلقِ على البنش بالبار المنحني. أنزل للجبهة بثني المرفقين فقط.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    sortOrder: 150,
  },
  {
    name: "Single-Arm Cable Curl",
    nameAr: "كيرل كيبل بذراع واحدة",
    category: "isolation" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
    difficulty: "beginner" as const,
    instructions: "Stand at low cable. Curl one arm up keeping elbow stationary. Switch arms.",
    instructionsAr: "قف عند الكيبل السفلي. ارفع بذراع واحدة مع تثبيت المرفق. بدّل.",
    contraindications: ["elbow"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    sortOrder: 151,
  },
  {
    name: "Lying Leg Curl",
    nameAr: "ثني أرجل مستلقي",
    category: "isolation" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["leg curl machine"],
    difficulty: "beginner" as const,
    instructions: "Lie face down. Curl pad toward glutes. Lower with control.",
    instructionsAr: "استلقِ على بطنك. ارفع الوسادة نحو المؤخرة. أنزل بتحكم.",
    contraindications: ["knee"],
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 152,
  },
  {
    name: "Standing Calf Raise",
    nameAr: "رفع ساق واقف",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["calf raise machine"],
    difficulty: "beginner" as const,
    instructions:
      "Stand with shoulders under pads. Rise on toes as high as possible. Lower slowly.",
    instructionsAr: "قف والكتفين تحت الوسائد. ارتفع على أصابعك بأقصى ارتفاع. أنزل ببطء.",
    contraindications: [],
    defaultSets: 3,
    defaultRepsMin: 15,
    defaultRepsMax: 20,
    defaultRestSeconds: 45,
    sortOrder: 153,
  },
  {
    name: "Cable Lateral Raise Behind",
    nameAr: "رفع جانبي كيبل خلفي",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
    difficulty: "intermediate" as const,
    instructions: "Cable runs behind body. Raise arm to side at shoulder height.",
    instructionsAr: "الكيبل خلف الجسم. ارفع الذراع جانبياً لمستوى الكتف.",
    contraindications: ["shoulder"],
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    sortOrder: 154,
  },
  {
    name: "Wrist Roller",
    nameAr: "لف الرسغ",
    category: "isolation" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
    equipment: ["wrist roller"],
    difficulty: "beginner" as const,
    instructions: "Hold roller at arm's length. Roll weight up by rotating wrists. Reverse.",
    instructionsAr: "امسك اللفافة بطول الذراعين. لف الوزن للأعلى بتدوير الرسغين. اعكس.",
    contraindications: ["wrist"],
    defaultSets: 3,
    defaultRepsMin: 2,
    defaultRepsMax: 3,
    defaultRestSeconds: 60,
    sortOrder: 155,
  },
];

const WARMUP = [
  {
    name: "Arm Circles",
    nameAr: "دوائر الذراعين",
    category: "warmup" as const,
    movementPattern: "rotation" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Extend arms out to sides. Make small circles, gradually increasing size.",
    instructionsAr: "مدد الذراعين للجانبين. ارسم دوائر صغيرة ثم كبّرها تدريجياً.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 20,
    defaultRepsMax: 20,
    defaultRestSeconds: 30,
    sortOrder: 61,
  },
  {
    name: "Leg Swings",
    nameAr: "تأرجح الساق",
    category: "warmup" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["hamstrings", "quads"],
    secondaryMuscles: ["hip"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Hold support. Swing leg forward and back in controlled motion.",
    instructionsAr: "أمسك بدعامة. أرجح الساق للأمام والخلف بحركة متحكمة.",
    contraindications: ["hip"],
    defaultSets: 1,
    defaultRepsMin: 15,
    defaultRepsMax: 15,
    defaultRestSeconds: 30,
    sortOrder: 62,
  },
  {
    name: "Hip Circles",
    nameAr: "دوائر الورك",
    category: "warmup" as const,
    movementPattern: "rotation" as const,
    primaryMuscles: ["hip", "glutes"],
    secondaryMuscles: ["core"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Hands on hips. Rotate hips in large circles. Switch directions.",
    instructionsAr: "ضع يديك على الوركين. دوّر الوركين بدوائر كبيرة. بدّل الاتجاه.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 10,
    defaultRepsMax: 10,
    defaultRestSeconds: 30,
    sortOrder: 63,
  },
  {
    name: "High Knees",
    nameAr: "ركبتين عالية",
    category: "warmup" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["quads", "core"],
    secondaryMuscles: ["calves"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Jog in place bringing knees to waist height. Pump arms.",
    instructionsAr: "اركض في مكانك مع رفع الركبتين لمستوى الخصر. حرّك الذراعين.",
    contraindications: ["knee"],
    defaultSets: 1,
    defaultRepsMin: 20,
    defaultRepsMax: 20,
    defaultRestSeconds: 30,
    sortOrder: 64,
  },
  {
    name: "Jumping Jacks",
    nameAr: "قفز جاك",
    category: "warmup" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["shoulders", "calves"],
    secondaryMuscles: ["quads"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Jump feet apart while raising arms overhead. Jump back to start.",
    instructionsAr: "اقفز بإبعاد القدمين مع رفع الذراعين. ارجع للوضع الأول.",
    contraindications: ["knee", "shoulder"],
    defaultSets: 1,
    defaultRepsMin: 20,
    defaultRepsMax: 20,
    defaultRestSeconds: 30,
    sortOrder: 65,
  },
  {
    name: "Bodyweight Squat",
    nameAr: "سكوات بوزن الجسم",
    category: "warmup" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Stand with feet shoulder-width. Squat down and stand up. Keep chest up.",
    instructionsAr: "قف بعرض الكتفين. انزل واقف. أبقِ الصدر مرفوعاً.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 15,
    defaultRepsMax: 15,
    defaultRestSeconds: 30,
    sortOrder: 66,
  },
  {
    name: "Inchworm",
    nameAr: "الدودة",
    category: "warmup" as const,
    movementPattern: "hinge" as const,
    primaryMuscles: ["core", "shoulders"],
    secondaryMuscles: ["hamstrings"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Bend at waist, walk hands out to plank. Walk hands back to feet. Stand up.",
    instructionsAr: "انحنِ من الخصر وامشِ بيديك للأمام لوضع البلانك. ارجع.",
    contraindications: ["lower back"],
    defaultSets: 1,
    defaultRepsMin: 8,
    defaultRepsMax: 8,
    defaultRestSeconds: 30,
    sortOrder: 67,
  },
  {
    name: "Cat-Cow",
    nameAr: "القطة والبقرة",
    category: "warmup" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["back", "core"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "On all fours. Arch back up (cat), then drop belly down (cow). Alternate slowly.",
    instructionsAr: "على أربع. قوّس الظهر للأعلى ثم أنزل البطن. بدّل ببطء.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 10,
    defaultRepsMax: 10,
    defaultRestSeconds: 30,
    sortOrder: 68,
  },
  {
    name: "Shoulder Dislocates",
    nameAr: "تدوير الكتف بالعصا",
    category: "warmup" as const,
    movementPattern: "rotation" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["chest"],
    equipment: ["resistance band"],
    difficulty: "beginner" as const,
    instructions: "Hold band wide overhead. Rotate arms behind body and back. Keep arms straight.",
    instructionsAr: "امسك الحبل بعرض فوق الرأس. دوّر الذراعين خلف الجسم وارجع.",
    contraindications: ["shoulder"],
    defaultSets: 1,
    defaultRepsMin: 10,
    defaultRepsMax: 10,
    defaultRestSeconds: 30,
    sortOrder: 69,
  },
  {
    name: "Butt Kicks",
    nameAr: "ركلات المؤخرة",
    category: "warmup" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["hamstrings", "quads"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Jog in place kicking heels toward glutes.",
    instructionsAr: "اركض في مكانك مع ركل الكعبين نحو المؤخرة.",
    contraindications: ["knee"],
    defaultSets: 1,
    defaultRepsMin: 20,
    defaultRepsMax: 20,
    defaultRestSeconds: 30,
    sortOrder: 70,
  },
  {
    name: "Walking Lunge",
    nameAr: "طعنات متحركة",
    category: "warmup" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Step forward into lunge. Push off front foot, step into next lunge.",
    instructionsAr: "اخطو للأمام بطعنة. ادفع من القدم الأمامية واستمر بالطعنة التالية.",
    contraindications: ["knee"],
    defaultSets: 1,
    defaultRepsMin: 10,
    defaultRepsMax: 10,
    defaultRestSeconds: 30,
    sortOrder: 71,
  },
  {
    name: "Band Pull-Apart",
    nameAr: "سحب الحبل",
    category: "warmup" as const,
    movementPattern: "pull" as const,
    primaryMuscles: ["rear_delts", "shoulders"],
    secondaryMuscles: ["back"],
    equipment: ["resistance band"],
    difficulty: "beginner" as const,
    instructions:
      "Hold band at arm's length, shoulder width. Pull apart stretching band across chest.",
    instructionsAr: "امسك الحبل بعرض الكتفين. اسحب لفتحه عبر الصدر.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 15,
    defaultRepsMax: 15,
    defaultRestSeconds: 30,
    sortOrder: 72,
  },
  {
    name: "Mountain Climbers",
    nameAr: "متسلق الجبال",
    category: "warmup" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["core", "quads"],
    secondaryMuscles: ["shoulders", "hamstrings"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Start in plank position. Alternate driving knees to chest quickly.",
    instructionsAr: "ابدأ بوضع البلانك. بدّل بين دفع الركبتين نحو الصدر بسرعة.",
    contraindications: ["wrist", "shoulder"],
    defaultSets: 1,
    defaultRepsMin: 20,
    defaultRepsMax: 20,
    defaultRestSeconds: 30,
    sortOrder: 73,
  },
  {
    name: "World's Greatest Stretch",
    nameAr: "أعظم تمدد في العالم",
    category: "warmup" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["hip", "hamstrings", "shoulders"],
    secondaryMuscles: ["core", "quads"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Lunge forward, place hands down, rotate torso opening one arm to ceiling. Alternate sides.",
    instructionsAr: "اخطو بطعنة للأمام، ضع يديك، دوّر الجذع بفتح ذراع للسقف. بدّل الجوانب.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 5,
    defaultRepsMax: 5,
    defaultRestSeconds: 30,
    sortOrder: 74,
  },
  {
    name: "Spiderman Lunge",
    nameAr: "طعنة سبايدرمان",
    category: "warmup" as const,
    movementPattern: "squat" as const,
    primaryMuscles: ["hip", "quads"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "From plank, step one foot outside same-side hand. Hold and return. Alternate.",
    instructionsAr: "من وضع البلانك، اخطو بقدم خارج اليد نفسها. ثبت وارجع. بدّل.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 8,
    defaultRepsMax: 8,
    defaultRestSeconds: 30,
    sortOrder: 75,
  },
  {
    name: "Scapular Push-Up",
    nameAr: "ضغط كتفي",
    category: "warmup" as const,
    movementPattern: "push" as const,
    primaryMuscles: ["shoulders", "back"],
    secondaryMuscles: ["core"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "In plank position, squeeze shoulder blades together then push them apart. Arms stay straight.",
    instructionsAr: "في وضع البلانك، اضغط لوحي الكتف معاً ثم ادفعهما بعيداً. الذراعان مستقيمتان.",
    contraindications: ["shoulder"],
    defaultSets: 1,
    defaultRepsMin: 10,
    defaultRepsMax: 10,
    defaultRestSeconds: 30,
    sortOrder: 76,
  },
  {
    name: "Dead Bug",
    nameAr: "الحشرة الميتة",
    category: "warmup" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["core"],
    secondaryMuscles: ["hip"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Lie on back, arms up, knees at 90 degrees. Extend opposite arm and leg. Return. Alternate.",
    instructionsAr:
      "استلقِ على الظهر، الذراعان للأعلى، الركبتان 90 درجة. مدد ذراع وساق معاكسين. بدّل.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 10,
    defaultRepsMax: 10,
    defaultRestSeconds: 30,
    sortOrder: 77,
  },
];

const COOLDOWN = [
  {
    name: "Chest Stretch",
    nameAr: "تمدد الصدر",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Place hand on wall at shoulder height. Turn body away to feel stretch in chest.",
    instructionsAr: "ضع يدك على الحائط بارتفاع الكتف. أدر جسمك بعيداً لتمدد الصدر.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 81,
  },
  {
    name: "Quad Stretch",
    nameAr: "تمدد الفخذ الأمامي",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Stand on one leg, pull other foot to glute. Hold for 20-30 seconds each side.",
    instructionsAr: "قف على ساق واسحب القدم الأخرى نحو المؤخرة. ثبت 20-30 ثانية لكل جانب.",
    contraindications: ["knee"],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 82,
  },
  {
    name: "Hamstring Stretch",
    nameAr: "تمدد الفخذ الخلفي",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Extend one leg forward on a raised surface. Hinge forward at hips. Hold 20-30 seconds.",
    instructionsAr: "مدد ساقاً على سطح مرتفع. انحنِ من الورك. ثبت 20-30 ثانية.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 83,
  },
  {
    name: "Shoulder Stretch",
    nameAr: "تمدد الكتف",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Bring one arm across body. Use opposite hand to pull it closer. Hold 20 seconds each.",
    instructionsAr: "ضع ذراعاً عبر الجسم. اسحبها بالأخرى. ثبت 20 ثانية لكل جانب.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 84,
  },
  {
    name: "Tricep Stretch",
    nameAr: "تمدد الترايسبس",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Raise one arm overhead, bend elbow. Use other hand to push elbow down. Hold 20 seconds.",
    instructionsAr: "ارفع ذراعاً وثنِ المرفق. ادفع المرفق بالأخرى. ثبت 20 ثانية.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 85,
  },
  {
    name: "Glute Stretch",
    nameAr: "تمدد المؤخرة",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hip"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Lie on back, cross one ankle over opposite knee. Pull bottom leg toward chest.",
    instructionsAr: "استلقِ على الظهر وضع كاحلاً فوق الركبة المقابلة. اسحب الساق السفلى نحو الصدر.",
    contraindications: ["hip"],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 86,
  },
  {
    name: "Child's Pose",
    nameAr: "وضعية الطفل",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["back", "shoulders"],
    secondaryMuscles: ["hip"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Kneel, sit back on heels, reach arms forward on floor. Breathe deeply.",
    instructionsAr: "اركع واجلس على الكعبين ومدد الذراعين للأمام. تنفس بعمق.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 87,
  },
  {
    name: "Cat-Cow Stretch",
    nameAr: "تمدد القطة والبقرة",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["back", "core"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "On all fours. Slowly arch and round back. Focus on breathing.",
    instructionsAr: "على أربع. قوّس الظهر وقرّبه ببطء. ركز على التنفس.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 10,
    defaultRepsMax: 10,
    defaultRestSeconds: 30,
    sortOrder: 88,
  },
  {
    name: "Hip Flexor Stretch",
    nameAr: "تمدد عضلة الورك",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["hip", "quads"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Kneel on one knee. Push hips forward until stretch in front of hip. Hold 20-30 seconds.",
    instructionsAr: "اركع على ركبة واحدة. ادفع الوركين للأمام. ثبت 20-30 ثانية.",
    contraindications: ["knee"],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 89,
  },
  {
    name: "Calf Stretch",
    nameAr: "تمدد ربلة الساق",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Stand facing wall, one foot back. Push heel down and lean into wall. Hold 20 seconds.",
    instructionsAr: "قف أمام الحائط وقدم للخلف. ادفع الكعب للأسفل واتكئ. ثبت 20 ثانية.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 90,
  },
  {
    name: "Lat Stretch",
    nameAr: "تمدد الظهر العريض",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["back"],
    secondaryMuscles: ["shoulders"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions: "Hold pole or doorframe overhead. Lean away to feel stretch along side of back.",
    instructionsAr: "أمسك بعمود فوق الرأس. اتّكئ بعيداً لتمدد جانب الظهر.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 91,
  },
  {
    name: "Deep Breathing",
    nameAr: "تنفس عميق",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Sit or lie down. Breathe in for 4 counts, hold for 4, out for 6. Repeat 5 times.",
    instructionsAr: "اجلس أو استلقِ. تنفس لـ4 عدات، ثبت لـ4، أخرج لـ6. كرر 5 مرات.",
    contraindications: [],
    defaultSets: 1,
    defaultRepsMin: 5,
    defaultRepsMax: 5,
    defaultRestSeconds: 60,
    sortOrder: 92,
  },
  {
    name: "Pigeon Pose",
    nameAr: "وضعية الحمامة",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["glutes", "hip"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "From all fours, bring one knee forward. Extend other leg back. Lean forward. Hold 30 seconds each.",
    instructionsAr:
      "من أربع، اجلب ركبة للأمام. مدد الساق الأخرى للخلف. انحنِ للأمام. ثبت 30 ثانية لكل جانب.",
    contraindications: ["hip", "knee"],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 93,
  },
  {
    name: "Supine Spinal Twist",
    nameAr: "لف العمود الفقري مستلقي",
    category: "cooldown" as const,
    movementPattern: "rotation" as const,
    primaryMuscles: ["back", "core"],
    secondaryMuscles: ["hip"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Lie on back. Bring one knee across body to opposite side. Arms out. Hold 20-30 seconds each.",
    instructionsAr:
      "استلقِ على الظهر. اجلب ركبة عبر الجسم للجانب المقابل. الذراعان ممدودتان. ثبت 20-30 ثانية.",
    contraindications: ["lower back"],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 94,
  },
  {
    name: "Doorway Chest Stretch",
    nameAr: "تمدد صدر عند الباب",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["chest", "shoulders"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Stand in doorway with arms on frame at 90 degrees. Lean forward until stretch. Hold 20-30 seconds.",
    instructionsAr:
      "قف في إطار الباب والذراعين عند 90 درجة. انحنِ للأمام حتى تشعر بالتمدد. ثبت 20-30 ثانية.",
    contraindications: ["shoulder"],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 95,
  },
  {
    name: "Figure-4 Stretch",
    nameAr: "تمدد الرقم 4",
    category: "cooldown" as const,
    movementPattern: "other" as const,
    primaryMuscles: ["glutes", "hip"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Lie on back. Cross one ankle over opposite knee. Pull bottom leg toward chest. Hold 20-30 seconds.",
    instructionsAr:
      "استلقِ على الظهر. ضع كاحلاً فوق الركبة المقابلة. اسحب الساق السفلى. ثبت 20-30 ثانية.",
    contraindications: ["hip"],
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 30,
    sortOrder: 96,
  },
  {
    name: "Prone Scorpion",
    nameAr: "العقرب",
    category: "cooldown" as const,
    movementPattern: "rotation" as const,
    primaryMuscles: ["hip", "back"],
    secondaryMuscles: ["core"],
    equipment: [],
    difficulty: "beginner" as const,
    instructions:
      "Lie face down, arms out. Lift one foot and reach it toward opposite hand. Alternate sides.",
    instructionsAr:
      "استلقِ على البطن والذراعان ممدودتان. ارفع قدماً نحو اليد المقابلة. بدّل الجوانب.",
    contraindications: ["lower back"],
    defaultSets: 1,
    defaultRepsMin: 8,
    defaultRepsMax: 8,
    defaultRestSeconds: 30,
    sortOrder: 97,
  },
];

// ---------------------------------------------------------------------------
// Seed mutations
// ---------------------------------------------------------------------------

export const seedExercises = internalMutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("exerciseDatabase").first();
    if (existing) {
      console.log(
        "[Seed] Exercise database already has data — skipping. Use clearExercises first to re-seed.",
      );
      return { inserted: 0, skipped: true };
    }

    const allExercises = [...COMPOUNDS, ...ACCESSORY, ...ISOLATION, ...WARMUP, ...COOLDOWN];

    // Insert in batches via internal mutation
    const batchSize = 50;
    let inserted = 0;
    for (let i = 0; i < allExercises.length; i += batchSize) {
      const batch = allExercises.slice(i, i + batchSize);
      await ctx.runMutation(internal.exerciseDatabase.bulkInsert, { exercises: batch });
      inserted += batch.length;
    }

    console.log(`[Seed] Inserted ${inserted} exercises successfully.`);
    return { inserted, skipped: false };
  },
});

export const clearExercises = internalMutation({
  args: {},
  handler: async (ctx) => {
    const exercises = await ctx.db.query("exerciseDatabase").collect();
    let deleted = 0;
    for (const ex of exercises) {
      await ctx.db.delete(ex._id);
      deleted++;
    }
    console.log(`[Seed] Deleted ${deleted} exercises.`);
    return { deleted };
  },
});
