/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as OnboardingRouteImport } from "./routes/_onboarding";
import { Route as DashboardRouteImport } from "./routes/_dashboard";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as DashboardIndexRouteImport } from "./routes/_dashboard/index";
import { Route as OnboardingWelcomeRouteImport } from "./routes/_onboarding/welcome";
import { Route as OnboardingPendingRouteImport } from "./routes/_onboarding/pending";
import { Route as OnboardingInitialAssessmentRouteImport } from "./routes/_onboarding/initial-assessment";
import { Route as DashboardWorkoutPlanRouteImport } from "./routes/_dashboard/workout-plan";
import { Route as DashboardTrackingRouteImport } from "./routes/_dashboard/tracking";
import { Route as DashboardProgressRouteImport } from "./routes/_dashboard/progress";
import { Route as DashboardMealPlanRouteImport } from "./routes/_dashboard/meal-plan";
import { Route as DashboardFaqRouteImport } from "./routes/_dashboard/faq";
import { Route as DashboardCheckInRouteImport } from "./routes/_dashboard/check-in";
import { Route as AuthSetPasswordRouteImport } from "./routes/_auth/set-password";
import { Route as AuthMagicLinkRouteImport } from "./routes/_auth/magic-link";
import { Route as AuthLoginRouteImport } from "./routes/_auth/login";
import { Route as AuthExpiredRouteImport } from "./routes/_auth/expired";
import { Route as AuthAcceptInviteRouteImport } from "./routes/_auth/accept-invite";
import { Route as DashboardTicketsIndexRouteImport } from "./routes/_dashboard/tickets/index";
import { Route as DashboardSettingsIndexRouteImport } from "./routes/_dashboard/settings/index";
import { Route as DashboardTicketsIdRouteImport } from "./routes/_dashboard/tickets/$id";
import { Route as DashboardSettingsAssessmentRouteImport } from "./routes/_dashboard/settings/assessment";

const OnboardingRoute = OnboardingRouteImport.update({
  id: "/_onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any);
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: "/welcome",
  path: "/welcome",
  getParentRoute: () => OnboardingRoute,
} as any);
const OnboardingPendingRoute = OnboardingPendingRouteImport.update({
  id: "/pending",
  path: "/pending",
  getParentRoute: () => OnboardingRoute,
} as any);
const OnboardingInitialAssessmentRoute = OnboardingInitialAssessmentRouteImport.update({
  id: "/initial-assessment",
  path: "/initial-assessment",
  getParentRoute: () => OnboardingRoute,
} as any);
const DashboardWorkoutPlanRoute = DashboardWorkoutPlanRouteImport.update({
  id: "/workout-plan",
  path: "/workout-plan",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardTrackingRoute = DashboardTrackingRouteImport.update({
  id: "/tracking",
  path: "/tracking",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: "/progress",
  path: "/progress",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardMealPlanRoute = DashboardMealPlanRouteImport.update({
  id: "/meal-plan",
  path: "/meal-plan",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardFaqRoute = DashboardFaqRouteImport.update({
  id: "/faq",
  path: "/faq",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardCheckInRoute = DashboardCheckInRouteImport.update({
  id: "/check-in",
  path: "/check-in",
  getParentRoute: () => DashboardRoute,
} as any);
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: "/set-password",
  path: "/set-password",
  getParentRoute: () => AuthRoute,
} as any);
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: "/magic-link",
  path: "/magic-link",
  getParentRoute: () => AuthRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any);
const AuthExpiredRoute = AuthExpiredRouteImport.update({
  id: "/expired",
  path: "/expired",
  getParentRoute: () => AuthRoute,
} as any);
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: "/accept-invite",
  path: "/accept-invite",
  getParentRoute: () => AuthRoute,
} as any);
const DashboardTicketsIndexRoute = DashboardTicketsIndexRouteImport.update({
  id: "/tickets/",
  path: "/tickets/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardTicketsIdRoute = DashboardTicketsIdRouteImport.update({
  id: "/tickets/$id",
  path: "/tickets/$id",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSettingsAssessmentRoute = DashboardSettingsAssessmentRouteImport.update({
  id: "/settings/assessment",
  path: "/settings/assessment",
  getParentRoute: () => DashboardRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof DashboardIndexRoute;
  "/accept-invite": typeof AuthAcceptInviteRoute;
  "/expired": typeof AuthExpiredRoute;
  "/login": typeof AuthLoginRoute;
  "/magic-link": typeof AuthMagicLinkRoute;
  "/set-password": typeof AuthSetPasswordRoute;
  "/check-in": typeof DashboardCheckInRoute;
  "/faq": typeof DashboardFaqRoute;
  "/meal-plan": typeof DashboardMealPlanRoute;
  "/progress": typeof DashboardProgressRoute;
  "/tracking": typeof DashboardTrackingRoute;
  "/workout-plan": typeof DashboardWorkoutPlanRoute;
  "/initial-assessment": typeof OnboardingInitialAssessmentRoute;
  "/pending": typeof OnboardingPendingRoute;
  "/welcome": typeof OnboardingWelcomeRoute;
  "/settings/assessment": typeof DashboardSettingsAssessmentRoute;
  "/tickets/$id": typeof DashboardTicketsIdRoute;
  "/settings/": typeof DashboardSettingsIndexRoute;
  "/tickets/": typeof DashboardTicketsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof DashboardIndexRoute;
  "/accept-invite": typeof AuthAcceptInviteRoute;
  "/expired": typeof AuthExpiredRoute;
  "/login": typeof AuthLoginRoute;
  "/magic-link": typeof AuthMagicLinkRoute;
  "/set-password": typeof AuthSetPasswordRoute;
  "/check-in": typeof DashboardCheckInRoute;
  "/faq": typeof DashboardFaqRoute;
  "/meal-plan": typeof DashboardMealPlanRoute;
  "/progress": typeof DashboardProgressRoute;
  "/tracking": typeof DashboardTrackingRoute;
  "/workout-plan": typeof DashboardWorkoutPlanRoute;
  "/initial-assessment": typeof OnboardingInitialAssessmentRoute;
  "/pending": typeof OnboardingPendingRoute;
  "/welcome": typeof OnboardingWelcomeRoute;
  "/settings/assessment": typeof DashboardSettingsAssessmentRoute;
  "/tickets/$id": typeof DashboardTicketsIdRoute;
  "/settings": typeof DashboardSettingsIndexRoute;
  "/tickets": typeof DashboardTicketsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/_dashboard": typeof DashboardRouteWithChildren;
  "/_onboarding": typeof OnboardingRouteWithChildren;
  "/_auth/accept-invite": typeof AuthAcceptInviteRoute;
  "/_auth/expired": typeof AuthExpiredRoute;
  "/_auth/login": typeof AuthLoginRoute;
  "/_auth/magic-link": typeof AuthMagicLinkRoute;
  "/_auth/set-password": typeof AuthSetPasswordRoute;
  "/_dashboard/check-in": typeof DashboardCheckInRoute;
  "/_dashboard/faq": typeof DashboardFaqRoute;
  "/_dashboard/meal-plan": typeof DashboardMealPlanRoute;
  "/_dashboard/progress": typeof DashboardProgressRoute;
  "/_dashboard/tracking": typeof DashboardTrackingRoute;
  "/_dashboard/workout-plan": typeof DashboardWorkoutPlanRoute;
  "/_onboarding/initial-assessment": typeof OnboardingInitialAssessmentRoute;
  "/_onboarding/pending": typeof OnboardingPendingRoute;
  "/_onboarding/welcome": typeof OnboardingWelcomeRoute;
  "/_dashboard/": typeof DashboardIndexRoute;
  "/_dashboard/settings/assessment": typeof DashboardSettingsAssessmentRoute;
  "/_dashboard/tickets/$id": typeof DashboardTicketsIdRoute;
  "/_dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/_dashboard/tickets/": typeof DashboardTicketsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/accept-invite"
    | "/expired"
    | "/login"
    | "/magic-link"
    | "/set-password"
    | "/check-in"
    | "/faq"
    | "/meal-plan"
    | "/progress"
    | "/tracking"
    | "/workout-plan"
    | "/initial-assessment"
    | "/pending"
    | "/welcome"
    | "/settings/assessment"
    | "/tickets/$id"
    | "/settings/"
    | "/tickets/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/accept-invite"
    | "/expired"
    | "/login"
    | "/magic-link"
    | "/set-password"
    | "/check-in"
    | "/faq"
    | "/meal-plan"
    | "/progress"
    | "/tracking"
    | "/workout-plan"
    | "/initial-assessment"
    | "/pending"
    | "/welcome"
    | "/settings/assessment"
    | "/tickets/$id"
    | "/settings"
    | "/tickets";
  id:
    | "__root__"
    | "/_auth"
    | "/_dashboard"
    | "/_onboarding"
    | "/_auth/accept-invite"
    | "/_auth/expired"
    | "/_auth/login"
    | "/_auth/magic-link"
    | "/_auth/set-password"
    | "/_dashboard/check-in"
    | "/_dashboard/faq"
    | "/_dashboard/meal-plan"
    | "/_dashboard/progress"
    | "/_dashboard/tracking"
    | "/_dashboard/workout-plan"
    | "/_onboarding/initial-assessment"
    | "/_onboarding/pending"
    | "/_onboarding/welcome"
    | "/_dashboard/"
    | "/_dashboard/settings/assessment"
    | "/_dashboard/tickets/$id"
    | "/_dashboard/settings/"
    | "/_dashboard/tickets/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  DashboardRoute: typeof DashboardRouteWithChildren;
  OnboardingRoute: typeof OnboardingRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_onboarding": {
      id: "/_onboarding";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard": {
      id: "/_dashboard";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard/": {
      id: "/_dashboard/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_onboarding/welcome": {
      id: "/_onboarding/welcome";
      path: "/welcome";
      fullPath: "/welcome";
      preLoaderRoute: typeof OnboardingWelcomeRouteImport;
      parentRoute: typeof OnboardingRoute;
    };
    "/_onboarding/pending": {
      id: "/_onboarding/pending";
      path: "/pending";
      fullPath: "/pending";
      preLoaderRoute: typeof OnboardingPendingRouteImport;
      parentRoute: typeof OnboardingRoute;
    };
    "/_onboarding/initial-assessment": {
      id: "/_onboarding/initial-assessment";
      path: "/initial-assessment";
      fullPath: "/initial-assessment";
      preLoaderRoute: typeof OnboardingInitialAssessmentRouteImport;
      parentRoute: typeof OnboardingRoute;
    };
    "/_dashboard/workout-plan": {
      id: "/_dashboard/workout-plan";
      path: "/workout-plan";
      fullPath: "/workout-plan";
      preLoaderRoute: typeof DashboardWorkoutPlanRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/tracking": {
      id: "/_dashboard/tracking";
      path: "/tracking";
      fullPath: "/tracking";
      preLoaderRoute: typeof DashboardTrackingRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/progress": {
      id: "/_dashboard/progress";
      path: "/progress";
      fullPath: "/progress";
      preLoaderRoute: typeof DashboardProgressRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/meal-plan": {
      id: "/_dashboard/meal-plan";
      path: "/meal-plan";
      fullPath: "/meal-plan";
      preLoaderRoute: typeof DashboardMealPlanRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/faq": {
      id: "/_dashboard/faq";
      path: "/faq";
      fullPath: "/faq";
      preLoaderRoute: typeof DashboardFaqRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/check-in": {
      id: "/_dashboard/check-in";
      path: "/check-in";
      fullPath: "/check-in";
      preLoaderRoute: typeof DashboardCheckInRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_auth/set-password": {
      id: "/_auth/set-password";
      path: "/set-password";
      fullPath: "/set-password";
      preLoaderRoute: typeof AuthSetPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/magic-link": {
      id: "/_auth/magic-link";
      path: "/magic-link";
      fullPath: "/magic-link";
      preLoaderRoute: typeof AuthMagicLinkRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/expired": {
      id: "/_auth/expired";
      path: "/expired";
      fullPath: "/expired";
      preLoaderRoute: typeof AuthExpiredRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/accept-invite": {
      id: "/_auth/accept-invite";
      path: "/accept-invite";
      fullPath: "/accept-invite";
      preLoaderRoute: typeof AuthAcceptInviteRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_dashboard/tickets/": {
      id: "/_dashboard/tickets/";
      path: "/tickets";
      fullPath: "/tickets/";
      preLoaderRoute: typeof DashboardTicketsIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/settings/": {
      id: "/_dashboard/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/tickets/$id": {
      id: "/_dashboard/tickets/$id";
      path: "/tickets/$id";
      fullPath: "/tickets/$id";
      preLoaderRoute: typeof DashboardTicketsIdRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/settings/assessment": {
      id: "/_dashboard/settings/assessment";
      path: "/settings/assessment";
      fullPath: "/settings/assessment";
      preLoaderRoute: typeof DashboardSettingsAssessmentRouteImport;
      parentRoute: typeof DashboardRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute;
  AuthExpiredRoute: typeof AuthExpiredRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute;
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthExpiredRoute: AuthExpiredRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface DashboardRouteChildren {
  DashboardCheckInRoute: typeof DashboardCheckInRoute;
  DashboardFaqRoute: typeof DashboardFaqRoute;
  DashboardMealPlanRoute: typeof DashboardMealPlanRoute;
  DashboardProgressRoute: typeof DashboardProgressRoute;
  DashboardTrackingRoute: typeof DashboardTrackingRoute;
  DashboardWorkoutPlanRoute: typeof DashboardWorkoutPlanRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardSettingsAssessmentRoute: typeof DashboardSettingsAssessmentRoute;
  DashboardTicketsIdRoute: typeof DashboardTicketsIdRoute;
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute;
  DashboardTicketsIndexRoute: typeof DashboardTicketsIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCheckInRoute: DashboardCheckInRoute,
  DashboardFaqRoute: DashboardFaqRoute,
  DashboardMealPlanRoute: DashboardMealPlanRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardTrackingRoute: DashboardTrackingRoute,
  DashboardWorkoutPlanRoute: DashboardWorkoutPlanRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsAssessmentRoute: DashboardSettingsAssessmentRoute,
  DashboardTicketsIdRoute: DashboardTicketsIdRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardTicketsIndexRoute: DashboardTicketsIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(DashboardRouteChildren);

interface OnboardingRouteChildren {
  OnboardingInitialAssessmentRoute: typeof OnboardingInitialAssessmentRoute;
  OnboardingPendingRoute: typeof OnboardingPendingRoute;
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute;
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingInitialAssessmentRoute: OnboardingInitialAssessmentRoute,
  OnboardingPendingRoute: OnboardingPendingRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
};

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(OnboardingRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
